// <auto-generated />
using System.Reflection;
using MediaMatch.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MediaMatch.Migrations
{
    [DbContext(typeof(MediaMatchContext))]
    [Migration("20251204180500_AddPasswordResetFields")]
    partial class AddPasswordResetFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            var snapshot = new MediaMatchContextModelSnapshot();
            var buildModelMethod = typeof(MediaMatchContextModelSnapshot).GetMethod(
                "BuildModel",
                BindingFlags.Instance | BindingFlags.NonPublic);
            buildModelMethod?.Invoke(snapshot, new object[] { modelBuilder });
#pragma warning restore 612, 618
        }
    }
}
